global:
  sendAnonymousUsage: true

log:
  level: INFO

api:
  dashboard: true

#accessLog: {}

entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: :443
  websocket:
    address: :8081
  mqtt:
    address: :8883
  
providers:
  file:
    directory: /etc/traefik/traefik.d/
    watch: true
  docker:
    watch: true
    exposedByDefault: false

certificatesResolvers:
  default:
    acme:
      caServer: https://acme-v02.api.letsencrypt.org/directory
      storage: /acme/acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0
        resolvers:
          - 1.1.1.1:53
          - 1.0.0.1:53
