- id: Update Available Notification
  alias: Update Available Notification
  trigger:
  - platform: state
    entity_id: binary_sensor.updater
    from: 'off'
    to: 'on'
  action:
  - service: notify.notify
    data_template:
      message: Home Assistant {{ state_attr('binary_sensor.updater', 'newest_version')
        }} is available.
- id: Balcony door opened
  alias: Balcony door opened
  trigger:
  - entity_id: binary_sensor.balcony_door_contact
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      message: The balcony door was opened.
    service: notify.mobile_app_marks_iphone
- id: Balcony door closed
  alias: Balcony door closed
  trigger:
  - entity_id: binary_sensor.balcony_door_contact
    from: 'on'
    platform: state
    to: 'off'
  action:
  - data:
      message: The balcony door was closed.
    service: notify.mobile_app_marks_iphone
- id: Front door opened
  alias: Front door opened
  trigger:
  - entity_id: binary_sensor.front_door_contact
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: The front door was opened.
    service: notify.mobile_app_marks_iphone
- id: Front door closed
  alias: Front door closed
  trigger:
  - entity_id: binary_sensor.front_door_contact
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: The front door was closed.
    service: notify.mobile_app_marks_iphone
- id: '1593540051379'
  alias: Evening
  description: ''
  trigger:
  - at: '17:30'
    platform: time
  - entity_id: person.mark
    platform: state
    to: home
  condition:
  - condition: state
    entity_id: person.mark
    state: home
  - after: '17:30'
    before: '21:00'
    condition: time
  action:
  - scene: scene.bedroom_evening
- id: '1593547399083'
  alias: Home Late
  description: ''
  trigger:
  - entity_id: person.mark
    platform: state
    to: home
  condition:
  - after: '21:00'
    before: 00:00
    condition: time
  action:
  - scene: scene.bedroom_bedtime
- id: '1593549200767'
  alias: Bedtime
  description: ''
  trigger:
  - at: '21:30'
    platform: time
  - entity_id: person.mark
    platform: state
    to: home
  condition:
  - condition: state
    entity_id: person.mark
    state: home
  - after: '21:30'
    before: 00:00
    condition: time
  - condition: state
    entity_id: input_boolean.bedtime_triggered
    state: 'off'
  action:
  - scene: scene.bedroom_bedtime
  - data: {}
    entity_id: input_boolean.bedtime_triggered
    service: input_boolean.turn_on
- id: '1593549830579'
  alias: Away Mode
  description: ''
  trigger:
  - entity_id: person.mark
    platform: state
    to: not_home
  condition: []
  action:
  - data: {}
    entity_id: all
    service: light.turn_off
- id: '1593716041042'
  alias: Morning Reset
  description: ''
  trigger:
  - at: 05:00
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: input_boolean.bedtime_triggered
    service: input_boolean.turn_off
