- id: 43e3418860ea4a24bc3757cd932e841f
  alias: Update Available Notification
  trigger:
    - platform: state
      entity_id: binary_sensor.updater
      from: 'off'
      to: 'on'
  action:
    - service: notify.notify
      data_template:
        message: Home Assistant {{ state_attr('binary_sensor.updater', 'newest_version') }} is available.

- id: '1580671753587'
  alias: Balcony door opened
  trigger:
    - entity_id: binary_sensor.balcony_door_sensor
      platform: state
      from: 'off'
      to: 'on'
  action:
    - service: notify.mobile_app_iphone
      data:
        message: The balcony door was opened.

- id: '1580672226784'
  alias: Balcony door closed
  trigger:
    - entity_id: binary_sensor.balcony_door_sensor
      platform: state
      from: 'on'
      to: 'off'
  action:
    - service: notify.mobile_app_iphone
      data:
        message: The balcony door was closed.
  
- id: '1580830517508'
  alias: Front door opened
  trigger:
    - entity_id: binary_sensor.front_door_sensor
      platform: state
      from: 'off'
      to: 'on'
  action:
    - service: notify.mobile_app_iphone
      data:
        message: The front door was opened.
  
- id: '1580830517509'
  alias: Front door closed
  trigger:
    - entity_id: binary_sensor.front_door_sensor
      platform: state
      from: 'on'
      to: 'off'
  action:
    - service: notify.mobile_app_iphone
      data:
        message: The front door was closed.
      