homeassistant:
  name: Home
  unit_system: metric
  time_zone: Europe/London

  # Location used by weather etc
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation

  customize: !include customize.yaml
  packages: !include_dir_named packages
  whitelist_external_dirs:
    - /tmp
  auth_providers:
    - type: homeassistant

http:
  base_url: !secret base_url
  server_port: 8123
  login_attempts_threshold: 20
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1

# Text-to-Speech
tts:
  - platform: google_translate

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Mobile app integration
mobile_app:

# MQTT
mqtt:
  client_id: home-assistant-1
  broker: mqtt
  port: 1883
  #username: !secret mqtt_user
  #password: !secret mqtt_password

# Philips Hue
hue:
  bridges:
    - host: !secret hue_bridge_ip
      allow_hue_groups: false

unifi:
  controllers:
    - host: !secret unifi_controller_ip
      site: !secret unifi_controller_site
      ssid_filter: 
        - !secret unifi_controller_ssid
      dont_track_devices: true
      dont_track_wired_clients: true

# Access devices through HomeKit
homekit:
  safe_mode: true
  advertise_ip: !secret homekit_broadcast_ip
  port: 51828

# History
recorder:
  purge_interval: 1
  purge_keep_days: 2
  #db_url: !secret recorder_db_url
history:
logbook:

influxdb:
  host: influxdb
  include:
    entities:
      - sensor.daylight
      - sensor.bedroom_multi_sensor_temperature
      - sensor.bedroom_multi_sensor_humidity
      - sensor.bedroom_multi_sensor_pressure
      - sensor.bedroom_multi_sensor_battery_level
      - sensor.kitchen_multi_sensor_temperature
      - sensor.kitchen_multi_sensor_pressure
      - sensor.kitchen_multi_sensor_humidity
      - sensor.kitchen_multi_sensor_battery_level
      - sensor.living_room_multi_sensor_temperature
      - sensor.living_room_multi_sensor_pressure
      - sensor.living_room_multi_sensor_humidity
      - sensor.living_room_multi_sensor_battery_level
      - sensor.lunas_room_multi_sensor_temperature
      - sensor.lunas_room_multi_sensor_pressure
      - sensor.lunas_room_multi_sensor_humidity
      - sensor.lunas_room_multi_sensor_battery_level
      - sensor.front_door_sensor_battery_level
      - sensor.balcony_door_sensor_battery_level
      - binary_sensor.front_door_sensor
      - binary_sensor.balcony_door_sensor

map:

updater:

system_health:

sun:

weather:
#  - platform: metoffice
#    api_key: !secret metoffice_api_key
#    name: Met Office

zone:
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 50
    icon: mdi:home
  - name: Work
    latitude: !secret work_latitude
    longitude: !secret work_longitude
    radius: 50
    icon: mdi:office-building

binary_sensor:
  - platform: workday
    country: England
    name: Workday

sensor: !include sensor.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
