homeassistant:
  name: Home
  unit_system: metric
  time_zone: Europe/London

  # Location used by weather etc
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation

  customize: !include customize.yaml
  packages: !include_dir_named packages
  whitelist_external_dirs:
    - /tmp
  auth_providers:
    - type: homeassistant

http:
  base_url: !secret base_url
  server_port: 8123
  login_attempts_threshold: 20
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1

# Text-to-Speech
tts:
  - platform: google_translate
    service_name: google_say
    language: 'en-uk'

# Enables the frontend
frontend:

# UI panels
panel_iframe:
  nodered:
    title: Node-RED
    icon: mdi:shuffle-variant
    url: https://home.xmple.io/nodered/

# Enables configuration UI
config:

discovery:

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

# Mobile app integration
mobile_app:

# MQTT
mqtt:
  discovery: true
  client_id: home-assistant-1
  broker: mqtt
  port: 1883
  #username: !secret mqtt_user
  #password: !secret mqtt_password
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

# Philips Hue
hue:
  bridges:
    - host: !secret hue_bridge_ip
      allow_hue_groups: false

unifi:
  controllers:
    - host: !secret unifi_controller_ip
      site: !secret unifi_controller_site
      dont_track_clients: false
      dont_track_devices: true
      dont_track_wired_clients: true
      detection_time: 600
      ssid_filter: 
        - !secret unifi_controller_ssid

person:
  - name: Mark
    id: mark
    user_id: !secret ha_user_id_mark
    device_trackers:
      - device_tracker.app_iphone_mark
  - name: Eleonora
    id: eleonora
    device_trackers:
      - device_tracker.unifi_iphone_eleonora

# Access devices through HomeKit
homekit:
  advertise_ip: !secret homekit_broadcast_ip
  port: 51828

# History
recorder:
  purge_interval: 1
  purge_keep_days: 2
  #db_url: !secret recorder_db_url
history:
logbook:

influxdb:
  host: influxdb
  include:
    entities:
      - weather.dark_sky
      - sensor.daylight
      - sensor.climate_bedroom_temperature
      - sensor.climate_bedroom_humidity
      - sensor.climate_bedroom_pressure
      - sensor.climate_bedroom_battery
      - sensor.climate_kitchen_temperature
      - sensor.climate_kitchen_pressure
      - sensor.climate_kitchen_humidity
      - sensor.climate_kitchen_battery
      - sensor.climate_livingroom_temperature
      - sensor.climate_livingroom_pressure
      - sensor.climate_livingroom_humidity
      - sensor.climate_livingroom_battery
      - sensor.climate_lunas_room_temperature
      - sensor.climate_lunas_room_pressure
      - sensor.climate_lunas_room_humidity
      - sensor.climate_lunas_room_battery
      - sensor.front_door_battery
      - sensor.balcony_door_battery
      - sensor.bathroom_window_battery
      - sensor.kitchen_window_battery
      - binary_sensor.front_door_contact
      - binary_sensor.balcony_door_contact
      - binary_sensor.bathroom_window_contact
      - binary_sensor.kitchen_window_contact
map:

updater:

system_health:

sun:

weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    latitude: !secret home_latitude
    longitude: !secret home_longitude

zone:
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 50
    icon: mdi:home
  - name: Work
    latitude: !secret work_latitude
    longitude: !secret work_longitude
    radius: 50
    icon: mdi:office-building

binary_sensor:
  - platform: workday
    country: England
    name: Workday

sensor: !include sensor.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
