homeassistant:
  name: Home
  unit_system: metric
  time_zone: Europe/London

  # Location used by weather etc
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation

  customize: !include customize.yaml
  packages: !include_dir_named packages
  whitelist_external_dirs:
    - /tmp
  auth_providers:
    - type: homeassistant

http:
  base_url: !secret base_url
  server_port: 8123
  login_attempts_threshold: 20
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1

# Text-to-Speech
tts:
  - platform: google_translate

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Mobile app integration
mobile_app:

# Access devices through HomeKit
homekit:
  safe_mode: true
  advertise_ip: !secret homekit_broadcast_ip
  port: 51828

# History
recorder:
  purge_interval: 1
  purge_keep_days: 2
  #db_url: !secret recorder_db_url
history:
logbook:

map:

updater:

system_health:

sun:

weather:
#  - platform: metoffice
#    api_key: !secret metoffice_api_key
#    name: Met Office

zone:
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 50
    icon: mdi:home
  - name: Work
    latitude: !secret work_latitude
    longitude: !secret work_longitude
    radius: 50
    icon: mdi:office-building

binary_sensor:
  - platform: workday
    country: England
    name: Workday

sensor: !include sensor.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
