homeassistant:
  name: Home
  unit_system: metric
  time_zone: Europe/London

  # Location used by weather etc
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation

  # Customization
  customize: !include customization/customize.yaml
  customize_domain: !include customization/domain.yaml
  customize_glob: !include customization/glob.yaml

  packages: !include_dir_named packages

  whitelist_external_dirs:
    - /tmp
  auth_providers:
    - type: homeassistant

http:
  server_port: 8123
  login_attempts_threshold: 20
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1

# Text-to-Speech
tts:
  - platform: google_translate
    service_name: google_say
    language: 'en-uk'

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes

# UI panels
panel_iframe:
  stats:
    title: Grafana
    icon: mdi:chart-areaspline
    url: https://home.xmple.io/grafana/d/pRwgexmgz/environment?orgId=1&refresh=1s&theme=light&kiosk=1&from=now-2d&to=now

# Enables configuration UI
config:

wake_on_lan:

discovery:

zeroconf:
  default_interface: true

homekit:
  advertise_ip: "10.1.1.20"
  port: 51827
  filter:
    exclude_domains:
      - automation
      - input_boolean
      - media_player
      - script

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

# Mobile app integration
mobile_app:

# MQTT
mqtt:
  discovery: true
  client_id: home-assistant-1
  broker: mqtt
  port: 1883
  #username: !secret mqtt_user
  #password: !secret mqtt_password
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

# Philips Hue
hue:
  bridges:
    - host: !secret hue_bridge_ip
      allow_hue_groups: false

sonos:
  media_player:
    hosts:
      - 10.1.1.121 # Bathroom
      - 10.1.1.197 # Livingroom
      - 10.1.1.118 # Kitchen
      - 10.1.1.184 # Snug
      - 10.1.1.114 # Bedroon
      - 10.1.1.133 # Luna's Room

dyson:
  username: !secret dyson_username
  password: !secret dyson_password
  language: GB
  devices:
    - device_id: !secret dyson_360eye_serial
      device_ip: !secret dyson_360eye_ip

samsungtv:
  - name: Samsung UE65KS9500 TV
    host: !secret livingroom_tv_ip
    turn_on_action:
      - service: wake_on_lan.send_magic_packet
        data:
          mac: "40:16:3b:0e:3f:f5"
      
# History
recorder:
  purge_keep_days: 2
  #db_url: !secret recorder_db_url
history:
logbook:

influxdb:
  host: influxdb
  include:
    entities:
      - weather.dark_sky
      - sensor.daylight
      - sensor.climate_bedroom_temperature
      - sensor.climate_bedroom_humidity
      - sensor.climate_bedroom_pressure
      - sensor.climate_bedroom_battery
      - sensor.climate_kitchen_temperature
      - sensor.climate_kitchen_pressure
      - sensor.climate_kitchen_humidity
      - sensor.climate_kitchen_battery
      - sensor.climate_livingroom_temperature
      - sensor.climate_livingroom_pressure
      - sensor.climate_livingroom_humidity
      - sensor.climate_livingroom_battery
      - sensor.climate_lunas_room_temperature
      - sensor.climate_lunas_room_pressure
      - sensor.climate_lunas_room_humidity
      - sensor.climate_lunas_room_battery
      - sensor.climate_snug_temperature
      - sensor.climate_snug_pressure
      - sensor.climate_snug_humidity
      - sensor.climate_snug_battery
      - sensor.front_door_battery
      - sensor.balcony_door_battery
      - sensor.bathroom_window_battery
      - sensor.kitchen_window_battery
      - binary_sensor.front_door_contact
      - binary_sensor.balcony_door_contact
      - binary_sensor.bathroom_window_contact
      - binary_sensor.kitchen_window_contact

map:

updater:

system_health:

sun:

zone:
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 50
    icon: mdi:home
  - name: Work
    latitude: !secret work_latitude
    longitude: !secret work_longitude
    radius: 50
    icon: mdi:office-building

sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
input_boolean: !include input_booleans.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
switch: !include switches.yaml
light: !include lights.yaml
weather: !include weather.yaml
person: !include persons.yaml
