homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://mqtt'
serial:
  adapter: deconz
  port: /dev/ttyACM0
advanced:
  channel: 15
  network_key:
    - 227
    - 174
    - 187
    - 155
    - 92
    - 46
    - 114
    - 219
    - 189
    - 222
    - 105
    - 8
    - 166
    - 84
    - 198
    - 79
  log_level: info
  log_output:
    - console
map_options:
  graphviz:
    colors:
      fill:
        enddevice: '#fff8ce'
        coordinator: '#e04e5d'
        router: '#4ea3e0'
      font:
        coordinator: '#ffffff'
        router: '#ffffff'
        enddevice: '#000000'
      line:
        active: '#009900'
        inactive: '#994444'
device_options:
  temperature_precision: 1
  humidity_precision: 1
devices:
  '0x00158d0004444fd8':
    friendly_name: climate_livingroom
  '0x00158d000427239d':
    friendly_name: climate_kitchen
  '0x00158d00041869a7':
    friendly_name: climate_lunas_room
  '0x00158d0004216d13':
    friendly_name: climate_bedroom
  '0x00158d00047bc420':
    friendly_name: climate_snug
  '0x00158d0004201937':
    friendly_name: front_door
  '0x00158d00040be15e':
    friendly_name: balcony_door
  '0x00158d00045bebda':
    friendly_name: kitchen_window
  '0x00158d00045c2898':
    friendly_name: bathroom_window
  '0x000d6ffffe7c159d':
    friendly_name: repeater_hallway
  '0x000d6ffffea05da1':
    friendly_name: repeater_livingroom
  '0x286d970001115bbf':
    friendly_name: motion_livingroom
  '0x286d970001115b00':
    friendly_name: motion_snug
  '0x286d9700011150f1':
    friendly_name: motion_bathroom
  '0x286d9700010bb6e3':
    friendly_name: motion_lunas_room
  '0x286d9700010c8eca':
    friendly_name: motion_bedroom
  '0x286d9700010c8af2':
    friendly_name: motion_kitchen
  '0x00178801060757a1':
    friendly_name: switch_bedroom
  '0x000d6ffffe6c28f1':
    friendly_name: dimmer_snug_centre
    homeassistant:
      brightness_scale: 240
  '0x001788010635e556':
    friendly_name: switch
  '0x0017880100f7e332':
    friendly_name: bedroom_bedside_right
  '0x0017880100f6ef2f':
    friendly_name: bedroom_bedside_left
  '0x000d6ffffe9d3379':
    friendly_name: dimmer_livingroom_centre
  '0x680ae2fffea1352c':
    friendly_name: 'light_snug_dresser'
