- platform: mqtt
  name: front_door_contact
  unique_id: front_door_contact
  state_topic: zigbee2mqtt/front_door
  availability_topic: zigbee2mqtt/bridge/state
  payload_on: false
  payload_off: true
  value_template: "{{ value_json.contact }}"
  device_class: door

- platform: mqtt
  name: balcony_door_contact
  unique_id: balcony_door_contact
  state_topic: zigbee2mqtt/balcony_door
  availability_topic: zigbee2mqtt/bridge/state
  payload_on: false
  payload_off: true
  value_template: "{{ value_json.contact }}"
  device_class: door

- platform: mqtt
  name: bathroom_window_contact
  unique_id: bathroom_window_contact
  state_topic: zigbee2mqtt/bathroom_window
  availability_topic: zigbee2mqtt/bridge/state
  payload_on: false
  payload_off: true
  value_template: "{{ value_json.contact }}"
  device_class: window

- platform: mqtt
  name: kitchen_window_contact
  unique_id: kitchen_window_contact
  state_topic: zigbee2mqtt/kitchen_window
  availability_topic: zigbee2mqtt/bridge/state
  payload_on: false
  payload_off: true
  value_template: "{{ value_json.contact }}"
  device_class: window
