# Climate snug
- platform: mqtt
  name: climate_snug_temperature
  unique_id: climate_snug_temperature
  state_topic: zigbee2mqtt/climate_snug
  availability_topic: zigbee2mqtt/bridge/state
  unit_of_measurement: °C
  device_class: temperature
  value_template: "{{ value_json.temperature }}"
- platform: mqtt
  name: climate_snug_humidity
  unique_id: climate_snug_humidity
  state_topic: zigbee2mqtt/climate_snug
  availability_topic: zigbee2mqtt/bridge/state
  unit_of_measurement: "%"
  device_class: humidity
  value_template: "{{ value_json.humidity }}"
- platform: mqtt
  name: climate_snug_pressure
  unique_id: climate_snug_pressure
  state_topic: zigbee2mqtt/climate_snug
  availability_topic: zigbee2mqtt/bridge/state
  unit_of_measurement: hPa
  device_class: pressure
  value_template: "{{ value_json.pressure }}"
- platform: mqtt
  name: climate_snug_battery
  unique_id: climate_snug_battery
  state_topic: zigbee2mqtt/climate_snug
  availability_topic: zigbee2mqtt/bridge/state
  unit_of_measurement: "%"
  device_class: battery
  value_template: "{{ value_json.battery }}"
- platform: mqtt
  name: climate_snug_linkquality
  state_topic: zigbee2mqtt/climate_snug
  availability_topic: zigbee2mqtt/bridge/state
  icon: mdi:signal
  unit_of_measurement: lqi
  value_template: "{{ value_json.linkquality }}"

# Climate kitchen
- platform: mqtt
  name: climate_kitchen_temperature
  unique_id: climate_kitchen_temperature
  state_topic: zigbee2mqtt/climate_kitchen
  availability_topic: zigbee2mqtt/bridge/state
  unit_of_measurement: °C
  device_class: temperature
  value_template: "{{ value_json.temperature }}"
- platform: mqtt
  name: climate_kitchen_humidity
  unique_id: climate_kitchen_humidity
  state_topic: zigbee2mqtt/climate_kitchen
  availability_topic: zigbee2mqtt/bridge/state
  unit_of_measurement: "%"
  device_class: humidity
  value_template: "{{ value_json.humidity }}"
- platform: mqtt
  name: climate_kitchen_pressure
  unique_id: climate_kitchen_pressure
  state_topic: zigbee2mqtt/climate_kitchen
  availability_topic: zigbee2mqtt/bridge/state
  unit_of_measurement: hPa
  device_class: pressure
  value_template: "{{ value_json.pressure }}"
- platform: mqtt
  name: climate_kitchen_battery
  unique_id: climate_kitchen_battery
  state_topic: zigbee2mqtt/climate_kitchen
  availability_topic: zigbee2mqtt/bridge/state
  unit_of_measurement: "%"
  device_class: battery
  value_template: "{{ value_json.battery }}"
- platform: mqtt
  name: climate_kitchen_linkquality
  unique_id: climate_kitchen_linkquality
  state_topic: zigbee2mqtt/climate_kitchen
  availability_topic: zigbee2mqtt/bridge/state
  icon: mdi:signal
  unit_of_measurement: lqi
  value_template: "{{ value_json.linkquality }}"

# Climate livingroom
- platform: mqtt
  name: climate_livingroom_temperature
  unique_id: climate_livingroom_temperature
  state_topic: zigbee2mqtt/climate_livingroom
  availability_topic: zigbee2mqtt/bridge/state
  unit_of_measurement: °C
  device_class: temperature
  value_template: "{{ value_json.temperature }}"
- platform: mqtt
  name: climate_livingroom_humidity
  unique_id: climate_livingroom_humidity
  state_topic: zigbee2mqtt/climate_livingroom
  availability_topic: zigbee2mqtt/bridge/state
  unit_of_measurement: "%"
  device_class: humidity
  value_template: "{{ value_json.humidity }}"
- platform: mqtt
  name: climate_livingroom_pressure
  unique_id: climate_livingroom_pressure
  state_topic: zigbee2mqtt/climate_livingroom
  availability_topic: zigbee2mqtt/bridge/state
  unit_of_measurement: hPa
  device_class: pressure
  value_template: "{{ value_json.pressure }}"
- platform: mqtt
  name: climate_livingroom_battery
  unique_id: climate_livingroom_battery
  state_topic: zigbee2mqtt/climate_livingroom
  availability_topic: zigbee2mqtt/bridge/state
  unit_of_measurement: "%"
  device_class: battery
  value_template: "{{ value_json.battery }}"
- platform: mqtt
  name: climate_livingroom_linkquality
  unique_id: climate_livingroom_linkquality
  state_topic: zigbee2mqtt/climate_livingroom
  availability_topic: zigbee2mqtt/bridge/state
  icon: mdi:signal
  unit_of_measurement: lqi
  value_template: "{{ value_json.linkquality }}"

# Climate luna's room
- platform: mqtt
  name: climate_lunas_room_temperature
  unique_id: climate_lunas_room_temperature
  state_topic: zigbee2mqtt/climate_lunas_room
  availability_topic: zigbee2mqtt/bridge/state
  unit_of_measurement: °C
  device_class: temperature
  value_template: "{{ value_json.temperature }}"
- platform: mqtt
  name: climate_lunas_room_humidity
  unique_id: climate_lunas_room_humidity
  state_topic: zigbee2mqtt/climate_lunas_room
  availability_topic: zigbee2mqtt/bridge/state
  unit_of_measurement: "%"
  device_class: humidity
  value_template: "{{ value_json.humidity }}"
- platform: mqtt
  name: climate_lunas_room_pressure
  unique_id: climate_lunas_room_pressure
  state_topic: zigbee2mqtt/climate_lunas_room
  availability_topic: zigbee2mqtt/bridge/state
  unit_of_measurement: hPa
  device_class: pressure
  value_template: "{{ value_json.pressure }}"
- platform: mqtt
  name: climate_lunas_room_battery
  unique_id: climate_lunas_room_battery
  state_topic: zigbee2mqtt/climate_lunas_room
  availability_topic: zigbee2mqtt/bridge/state
  unit_of_measurement: "%"
  device_class: battery
  value_template: "{{ value_json.battery }}"
- platform: mqtt
  name: climate_lunas_room_linkquality
  unique_id: climate_lunas_room_linkquality
  state_topic: zigbee2mqtt/climate_lunas_room
  availability_topic: zigbee2mqtt/bridge/state
  icon: mdi:signal
  unit_of_measurement: lqi
  value_template: "{{ value_json.linkquality }}"

# Climate bedroom
- platform: mqtt
  name: climate_bedroom_temperature
  unique_id: climate_bedroom_temperature
  state_topic: zigbee2mqtt/climate_bedroom
  availability_topic: zigbee2mqtt/bridge/state
  unit_of_measurement: °C
  device_class: temperature
  value_template: "{{ value_json.temperature }}"
- platform: mqtt
  name: climate_bedroom_humidity
  unique_id: climate_bedroom_humidity
  state_topic: zigbee2mqtt/climate_bedroom
  availability_topic: zigbee2mqtt/bridge/state
  unit_of_measurement: "%"
  device_class: humidity
  value_template: "{{ value_json.humidity }}"
- platform: mqtt
  name: climate_bedroom_pressure
  unique_id: climate_bedroom_pressure
  state_topic: zigbee2mqtt/climate_bedroom
  availability_topic: zigbee2mqtt/bridge/state
  unit_of_measurement: hPa
  device_class: pressure
  value_template: "{{ value_json.pressure }}"
- platform: mqtt
  name: climate_bedroom_battery
  unique_id: climate_bedroom_battery
  state_topic: zigbee2mqtt/climate_bedroom
  availability_topic: zigbee2mqtt/bridge/state
  unit_of_measurement: "%"
  device_class: battery
  value_template: "{{ value_json.battery }}"
- platform: mqtt
  name: climate_bedroom_linkquality
  unique_id: climate_bedroom_linkquality
  state_topic: zigbee2mqtt/climate_bedroom
  availability_topic: zigbee2mqtt/bridge/state
  icon: mdi:signal
  unit_of_measurement: lqi
  value_template: "{{ value_json.linkquality }}"

# Contact kitcheb window
- platform: mqtt
  name: kitchen_window_battery
  unique_id: kitchen_window_battery
  state_topic: zigbee2mqtt/kitchen_window
  availability_topic: zigbee2mqtt/bridge/state
  unit_of_measurement: "%"
  device_class: battery
  value_template: "{{ value_json.battery }}"
- platform: mqtt
  name: kitchen_window_linkquality
  unique_id: kitchen_window_linkquality
  state_topic: zigbee2mqtt/kitchen_window
  availability_topic: zigbee2mqtt/bridge/state
  icon: mdi:signal
  unit_of_measurement: lqi
  value_template: "{{ value_json.linkquality }}"

# Contact bathroom window
- platform: mqtt
  name: bathroom_window_battery
  unique_id: bathroom_window_battery
  state_topic: zigbee2mqtt/bathroom_window
  availability_topic: zigbee2mqtt/bridge/state
  unit_of_measurement: "%"
  device_class: battery
  value_template: "{{ value_json.battery }}"
- platform: mqtt
  name: bathroom_window_linkquality
  unique_id: bathroom_window_linkquality
  state_topic: zigbee2mqtt/bathroom_window
  availability_topic: zigbee2mqtt/bridge/state
  icon: mdi:signal
  unit_of_measurement: lqi
  value_template: "{{ value_json.linkquality }}"

# Contact front door
- platform: mqtt
  name: front_door_battery
  unique_id: front_door_battery
  state_topic: zigbee2mqtt/front_door
  availability_topic: zigbee2mqtt/bridge/state
  unit_of_measurement: "%"
  device_class: battery
  value_template: "{{ value_json.battery }}"
- platform: mqtt
  name: front_door_linkquality
  unique_id: front_door_linkquality
  state_topic: zigbee2mqtt/front_door
  availability_topic: zigbee2mqtt/bridge/state
  icon: mdi:signal
  unit_of_measurement: lqi
  value_template: "{{ value_json.linkquality }}"

# Contact balcony door
- platform: mqtt
  name: balcony_door_battery
  unique_id: balcony_door_battery
  state_topic: zigbee2mqtt/balcony_door
  availability_topic: zigbee2mqtt/bridge/state
  unit_of_measurement: "%"
  device_class: battery
  value_template: "{{ value_json.battery }}"
- platform: mqtt
  name: balcony_door_linkquality
  unique_id: balcony_door_linkquality
  state_topic: zigbee2mqtt/balcony_door
  availability_topic: zigbee2mqtt/bridge/state
  icon: mdi:signal
  unit_of_measurement: lqi
  value_template: "{{ value_json.linkquality }}"
